### PR TITLE
initial support for fluxctl tool

### PR DESCRIPTION
**Pull request by ctorrao**
this is a first approach to support the download and commands for the fluxctl tool, with the repo in here: https://github.com/fluxcd/flux

### CODE REVIEW

**Comment by ctorrao** [comment]
@TsuyoshiUshio, is it possible to add this PR and release a preview version with this feature?

**Comment by ctorrao** [comment]
@TsuyoshiUshio I already tried this extension in a private Azure DevOps and it's working correctly. Can you please review this PR and release a new version with this new feature?

**Comment by TsuyoshiUshio** [comment]
Hi @ctorrao Sorry, I didn't notice that! Thank you for your contribution. I'd happy to release it.  Could you make it major version up, please?  The reason is, Azure DevOps can only leave the major version up change. unless it, it override. That means it affect to the current users. If we make it major version up, the current user has no influence of this release and users can choose if they use stable old version or with new feature of yours. :)

**Comment by ctorrao** [comment]
> Hi @ctorrao Sorry, I didn't notice that! Thank you for your contribution. I'd happy to release it. Could you make it major version up, please? The reason is, Azure DevOps can only leave the major version up change. unless it, it override. That means it affect to the current users. If we make it major version up, the current user has no influence of this release and users can choose if they use stable old version or with new feature of yours. :)

Hi @TsuyoshiUshio. Already increased the major version of the extension it self and also all the tasks. Let me know if it's everything ok with the PR and also with the build process.

**Comment by TsuyoshiUshio** [comment]
Thank you @ctorrao . 
I'll merge it and release it soon. :) Now I'm about to travel.  It might take a couple of days. however, I'm surely do it. Thank you for the contribution.

**Pull request merged**
